version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: tweets_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tweet_sentiment
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4'
      --innodb-flush-log-at-trx-commit=0
      --innodb-flush-method=O_DIRECT
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "user",
          "--password=password",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  api:
    build: .
    container_name: flask_api
    restart: always
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/tweet_sentiment
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
